# Generated by Django 3.2.7 on 2021-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserStatus', models.BooleanField(default=False)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=100)),
                ('SelaId', models.CharField(max_length=50)),
            ],
        ),
    ]
