# Generated by Django 3.2.7 on 2021-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='UserStatus',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
