# Generated by Django 3.2.7 on 2021-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_userdata_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='SelaId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='UserStatus',
            field=models.IntegerField(default=1),
        ),
    ]
