# Generated by Django 3.2.7 on 2021-09-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20210908_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=12),
        ),
    ]
